name: statewithease
description: An easy-to-use, minimal library for managing state with very little boilerplate
version: 1.0.0
repository: https://github.com/TheUltimateOptimist/statewithease

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
